# -*- coding: utf-8 -*-
"""Test_autre_modele.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_toHXOwJwA-1yiY5x1QF7V3AwBjjpN8
"""

from google.colab import drive
drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/Challenge-Welding-Reference-Solution-1-main (1).zip"  # <-- adapte le nom ici si différent

!unzip -q "$zip_path" -d /content


!ls /content

!mv /content/Challenge-Welding-Reference-Solution-1-main /content/challenge_welding

!ls /content

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/challenge_welding
!ls

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive

!ls "/content/drive/MyDrive/zip"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!git clone https://github.com/confianceai/Challenge-Welding-Reference-Solution-1.git challenge_welding

!ls /content

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/challenge_welding
!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/challenge_welding
!pip install -e .

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/challenge_welding
!pip install "ml_dtypes>=0.5.0"



# Commented out IPython magic to ensure Python compatibility.
# %cd /content/challenge_welding
!sed -n '1,200p' challenge_solution/AIComponent.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/challenge_welding/challenge_solution/AIComponent.py
# from challenge_welding.ai_component_interface import AbstractAIComponent
# from pathlib import Path
# import numpy as np
# import torch
# import torch.nn as nn
# from PIL import Image
# 
# ROOT_PATH = Path(__file__).parent.resolve()
# device = "cuda" if torch.cuda.is_available() else "cpu"
# 
# # Petit modèle CNN maison (original, sans torchvision)
# class SimpleWeldCNN(nn.Module):
#     def __init__(self, num_classes=2):
#         super().__init__()
#         self.features = nn.Sequential(
#             nn.Conv2d(3, 16, kernel_size=3, stride=2, padding=1),
#             nn.ReLU(),
#             nn.Conv2d(16, 32, kernel_size=3, stride=2, padding=1),
#             nn.ReLU(),
#             nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1),
#             nn.ReLU(),
#             nn.AdaptiveAvgPool2d((1, 1)),
#         )
#         self.classifier = nn.Linear(64, num_classes)  # KO / OK
# 
#     def forward(self, x):
#         x = self.features(x)          # (B,64,1,1)
#         x = x.view(x.size(0), -1)     # (B,64)
#         x = self.classifier(x)        # (B,2)
#         return x
# 
# class MyAIComponent(AbstractAIComponent):
#     def __init__(self):
#         super().__init__()
#         self.model = None
#         self.conf_threshold = 0.6
# 
#     def load_model(self, config_file=None):
#         """
#         Instancie le modèle (pour aller vite on ne charge pas de poids entraînés).
#         """
#         self.model = SimpleWeldCNN(num_classes=2).to(device)
#         self.model.eval()
#         print(f"SimpleWeldCNN initialisé sur {device}")
# 
#     def _preprocess_images(self, input_images):
#         """
#         input_images : liste de np.ndarray (H, W, 3)
#         Sortie : batch torch.Tensor (B,3,128,128)
#         """
#         tensors = []
#         for img in input_images:
#             pil_img = Image.fromarray(img.astype(np.uint8))
#             pil_img = pil_img.resize((128, 128))
#             arr = np.array(pil_img).astype(np.float32) / 255.0  # (H,W,3)
#             arr = np.transpose(arr, (2, 0, 1))                  # (3,H,W)
#             t = torch.from_numpy(arr)
#             tensors.append(t)
#         batch = torch.stack(tensors, dim=0).to(device)
#         return batch
# 
#     def predict(self, input_images, images_meta_informations, device=None, **kwargs):
#         """
#         Signature compatible avec : predict(..., device='cuda')
#         On ignore 'device' et on utilise la variable globale 'device'.
#         """
#         x = self._preprocess_images(input_images)
# 
#         with torch.no_grad():
#             logits = self.model(x)
#             probs = torch.softmax(logits, dim=1).cpu().numpy()
# 
#         predictions = []
#         prob_list = []
#         ood_scores = []
# 
#         for p in probs:
#             p_ko = float(p[0])
#             p_ok = float(p[1])
#             max_p = max(p_ko, p_ok)
# 
#             ood_score = 0.0
# 
#             if max_p < self.conf_threshold:
#                 predictions.append("UNKNOWN")
#                 prob_list.append([p_ko/2, p_ok/2, 0.5])
#             else:
#                 if p_ko >= p_ok:
#                     predictions.append("KO")
#                 else:
#                     predictions.append("OK")
#                 prob_list.append([p_ko, p_ok, 0.0])
# 
#             ood_scores.append(ood_score)
# 
#         return {
#             "predictions": predictions,
#             "probabilities": prob_list,
#             "OOD_scores": ood_scores,
#         }
#

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/challenge_welding
!python 03-Test_AIComponent.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/challenge_welding

# Commented out IPython magic to ensure Python compatibility.
# %%writefile challenge_solution/AIComponent.py
# from challenge_welding.ai_component_interface import AbstractAIComponent
# from pathlib import Path
# import numpy as np
# import torch
# import torch.nn as nn
# from PIL import Image
# 
# ROOT_PATH = Path(__file__).parent.resolve()
# device = "cuda" if torch.cuda.is_available() else "cpu"
# 
# # 1. BLOCS DE BASE : ConvBlock + SEBlock
# 
# 
# class ConvBlock(nn.Module):
#     def __init__(self, in_ch, out_ch, k=3, s=1, p=1):
#         super().__init__()
#         self.conv = nn.Conv2d(in_ch, out_ch, kernel_size=k, stride=s, padding=p)
#         self.bn   = nn.BatchNorm2d(out_ch)
#         self.act  = nn.ReLU(inplace=True)
# 
#     def forward(self, x):
#         return self.act(self.bn(self.conv(x)))
# 
# 
# class SEBlock(nn.Module):
#     """ Squeeze-and-Excitation : attention sur les canaux """
#     def __init__(self, channels, reduction=16):
#         super().__init__()
#         self.pool = nn.AdaptiveAvgPool2d(1)
#         self.fc   = nn.Sequential(
#             nn.Linear(channels, channels // reduction),
#             nn.ReLU(inplace=True),
#             nn.Linear(channels // reduction, channels),
#             nn.Sigmoid()
#         )
# 
#     def forward(self, x):
#         b, c, _, _ = x.shape
#         y = self.pool(x).view(b, c)
#         y = self.fc(y).view(b, c, 1, 1)
#         return x * y
# 
# 
# # 2. MODELE ORIGINAL : DualPathWeldNet
# 
# 
# class DualPathWeldNet(nn.Module):
#     """
#     Architecture originale maison :
#     - Branche locale (CNN classique)
#     - Branche globale (kernels larges + Squeeze-and-Excitation)
#     - Fusion des deux chemins
#     """
#     def __init__(self, num_classes=2):
#         super().__init__()
# 
#         # Branche locale
#         self.local_block1 = ConvBlock(3, 32, k=3, s=2)
#         self.local_block2 = ConvBlock(32, 64, k=3, s=2)
#         self.local_block3 = ConvBlock(64, 128, k=3, s=2)
#         self.local_pool   = nn.AdaptiveAvgPool2d((1, 1))
# 
#         # Branche globale
#         self.global_block1 = ConvBlock(3, 32, k=5, s=2, p=2)
#         self.global_block2 = ConvBlock(32, 64, k=5, s=2, p=2)
#         self.global_se     = SEBlock(64, reduction=8)
#         self.global_pool   = nn.AdaptiveAvgPool2d((1, 1))
# 
#         # Fusion des 2 chemins
#         self.fc = nn.Sequential(
#             nn.Linear(128 + 64, 128),
#             nn.ReLU(inplace=True),
#             nn.Dropout(0.3),
#             nn.Linear(128, num_classes)
#         )
# 
#     def forward(self, x):
#         # Locale
#         xl = self.local_block1(x)
#         xl = self.local_block2(xl)
#         xl = self.local_block3(xl)
#         xl = self.local_pool(xl)
#         xl = xl.view(xl.size(0), -1)
# 
#         # Globale
#         xg = self.global_block1(x)
#         xg = self.global_block2(xg)
#         xg = self.global_se(xg)
#         xg = self.global_pool(xg)
#         xg = xg.view(xg.size(0), -1)
# 
#         # Fusion
#         x_cat = torch.cat([xl, xg], dim=1)
#         out   = self.fc(x_cat)
#         return out
# 
# 
# # 3. AIComponent INTÉGRÉ AU PIPELINE
# 
# 
# class MyAIComponent(AbstractAIComponent):
#     def __init__(self):
#         super().__init__()
#         self.model = None
#         self.conf_threshold = 0.6
# 
#     def load_model(self, config_file=None):
#         """ Chargement du modèle original """
#         self.model = DualPathWeldNet(num_classes=2).to(device)
# 
# 
#         self.model.eval()
#         print(f"DualPathWeldNet initialisé sur {device}")
# 
#     def _preprocess_images(self, input_images):
#         tensors = []
#         for img in input_images:
#             pil_img = Image.fromarray(img.astype(np.uint8))
#             pil_img = pil_img.resize((256, 256))
#             arr = np.array(pil_img).astype(np.float32) / 255.0
#             arr = np.transpose(arr, (2, 0, 1))
#             t = torch.from_numpy(arr)
#             tensors.append(t)
#         batch = torch.stack(tensors, dim=0).to(device)
#         return batch
# 
#     def predict(self, input_images, images_meta_informations, device=None, **kwargs):
#         x = self._preprocess_images(input_images)
# 
#         with torch.no_grad():
#             logits = self.model(x)
#             probs = torch.softmax(logits, dim=1).cpu().numpy()
# 
#         predictions, prob_list, ood_scores = [], [], []
# 
#         for p in probs:
#             p_ko, p_ok = float(p[0]), float(p[1])
#             max_p = max(p_ko, p_ok)
# 
#             # Score OOD basique
#             ood_score = 0.0
# 
#             if max_p < self.conf_threshold:
#                 predictions.append("UNKNOWN")
#                 prob_list.append([p_ko/2, p_ok/2, 0.5])
#             else:
#                 if p_ko >= p_ok:
#                     predictions.append("KO")
#                 else:
#                     predictions.append("OK")
#                 prob_list.append([p_ko, p_ok, 0.0])
# 
#             ood_scores.append(ood_score)
# 
#         return {
#             "predictions": predictions,
#             "probabilities": prob_list,
#             "OOD_scores": ood_scores,
#         }
#

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/challenge_welding
!python 03-Test_AIComponent.py